version: '1.0'
stages:
  - "init"
  - "build"
  - "push"

steps:
  define_the_versions_list:
    stage: 'init'
    image: alpine
    commands:
      - |-
        cat <<EOF > helmVersionsList
        3.8.0
        3.9.0
    when:
      condition:
        all:
          notRecursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == true'

  run-cli-loop:
    stage: 'init'
    image: codefresh/cli
    commands:
      - for VAR in $(cat helmVersionsList); do codefresh wait $(codefresh run ${{CF_PIPELINE_NAME}} -d --branch ${{CF_BRANCH}} --variable HELM_VERSION=${VAR} --trigger ${{CF_PIPELINE_TRIGGER_ID}} --context github && sleep 10) & done
      - for j in $(jobs -p); do wait $j || (echo "Failed to build one of the images" && ! break); done
    when:
      condition:
        all:
          notRecursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == true'

  debug:
    stage: 'build'
    type: freestyle
    image: alpine
    commands:
      - echo $HELM_VERSION
      - env | grep CF_
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  clone:
    stage: 'build'
    type: git-clone
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github-cf-api-token
      revision: '${{CF_REVISION}}'
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  build_image:
    stage: 'build'
    type: build
    registry: pysarenko
    working_directory: '${{clone}}'
    image_name: '${{STEP_IMAGE}}'
    tag: '${{HELM_VERSION}}-${{CF_SHORT_REVISION}}'
    build_arguments:
      - 'HELM_VERSION=${{HELM_VERSION}}'
      - 'S3_PLUGIN_VERSION=0.9.2'
      - 'GCS_PLUGIN_VERSION=0.3.0'
      - 'PUSH_PLUGIN_VERSION=0.8.1'
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  run_e2e:
    stage: 'build'
    type: codefresh-run
    arguments:
      FOLLOW_LOGS: false
      PIPELINE_ID: Helm/e2e
      DETACH: false
      # TRIGGER_ID: trigger
      # BRANCH: ${{CF_BRANCH}}
      RESET_VOLUME: true
      # VARIABLE_FILE: ${{CF_VOLUME_PATH}}/env_vars_to_run_pipe.yml
      VARIABLE:
        - HELM_VERSION=${{HELM_VERSION}}-${{CF_SHORT_REVISION}}
        - CF_BRANCH=${{CF_BRANCH}}
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'

  push:
    stage: 'push'
    type: push
    tag: ${{HELM_VERSION}}
    candidate: ${{build_image}}
    when:
      condition:
        all:
          recursivelyInvoked: 'includes("${{HELM_VERSION}}", "${{") == false'
          masterBranch: 'match("${{CF_BRANCH}}", "^master", true) == true'
    scale:
      PushToDockerHub:
        registry: pysarenko

